name: Publish to GHCR

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_push:
    name: Build image & push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - name: Extract version info
        id: version
        run: |
          VERSION=${GITHUB_REF_NAME}
          MAJOR_MINOR=$(echo $VERSION | cut -d. -f1,2)

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "MAJOR_MINOR=$MAJOR_MINOR" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg APP_VERSION=$VERSION \
            -t ghcr.io/${{ github.repository_owner }}/pdftoru:$VERSION \
            -t ghcr.io/${{ github.repository_owner }}/pdftoru:$MAJOR_MINOR \
            -t ghcr.io/${{ github.repository_owner }}/pdftoru:latest \
            .

      - name: Push images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/pdftoru:$VERSION
          docker push ghcr.io/${{ github.repository_owner }}/pdftoru:$MAJOR_MINOR
          docker push ghcr.io/${{ github.repository_owner }}/pdftoru:latest

      - name: Delete old container versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: pdftoru
          package-type: container
          min-versions-to-keep: 3